import { useState, useRef } from "react";
import { Shell } from "@/components/layout/Shell";
import { PhoneCall, PhoneOff, Shield, Mic, Volume2, AlertTriangle, CheckCircle, FileText, Download } from "lucide-react";
import { cn, playVoice } from "@/lib/utils";
import { format } from "date-fns";
import { useToast } from "@/hooks/use-toast";

const SCAMMER_SCRIPT = [
  {
    text: "Hello, am I speaking with the account holder? This is Vikram Sharma calling from SBI Fraud Prevention Team.",
    delay: 1500,
  },
  {
    text: "Sir, we have detected multiple suspicious transactions on your account in the last 30 minutes. Your account will be blocked in the next 2 hours if you do not verify your identity immediately.",
    delay: 3000,
  },
  {
    text: "I need you to confirm your 16-digit debit card number so I can flag it as legitimate and prevent the block.",
    delay: 2500,
  },
  {
    text: "Also sir, an OTP has been sent to your registered mobile. Please share it with me so I can verify you are the account owner.",
    delay: 2500,
  },
  {
    text: "Sir, please hurry. You have less than 5 minutes before the system automatically suspends your account. I am trying to help you.",
    delay: 3000,
  },
];

type Turn = { role: "scammer" | "agent"; text: string; timestamp: Date };
type CallState = "idle" | "ringing" | "active" | "ended" | "verdict";

function generateFIRFromCall(turns: Turn[], verdict: { scam: boolean; intel: any }): string {
  const date = format(new Date(), "dd/MM/yyyy HH:mm");
  return [
    "═══════════════════════════════════════════════════════",
    "           FIRST INFORMATION REPORT (FIR)",
    "              Phone Call / Voice Fraud",
    "═══════════════════════════════════════════════════════",
    "",
    `Date & Time       : ${date}`,
    `Case Type         : Phone Call Fraud / Vishing`,
    `Detection Method  : AI Honeypot (Call Shield)`,
    "",
    "SECTION 1: INCIDENT",
    "───────────────────────────────────────────────────────",
    "Suspect called posing as a bank fraud prevention officer.",
    "Attempted to extract: OTP, debit card number, account details.",
    "Tactics: Urgency creation, impersonation, fear tactics.",
    "",
    "SECTION 2: SUSPECT DETAILS",
    "───────────────────────────────────────────────────────",
    `Suspect Number    : +91-98765-43210 (spoofed)`,
    `Claimed Name      : Vikram Sharma`,
    `Claimed Org       : SBI Fraud Prevention Team`,
    "",
    "SECTION 3: CALL TRANSCRIPT",
    "───────────────────────────────────────────────────────",
    "",
    ...turns.map(t => [
      `[${format(t.timestamp, "HH:mm:ss")}] ${t.role === "scammer" ? "SUSPECT" : "AI AGENT"}:`,
      t.text,
      "",
    ]).flat(),
    "SECTION 4: VERDICT",
    "───────────────────────────────────────────────────────",
    `Classification    : ${verdict.scam ? "SCAM CALL CONFIRMED" : "LEGITIMATE"}`,
    "Confidence        : 94%",
    "Tactics Detected  : Urgency creation, impersonation, OTP phishing",
    "",
    "SECTION 5: COMPLAINANT (Fill before filing)",
    "───────────────────────────────────────────────────────",
    "Full Name         : ____________________________",
    "Mobile Number     : ____________________________",
    "Amount Lost (₹)   : ____________________________",
    "",
    "File at: cybercrime.gov.in  |  Helpline: 1930",
    "═══════════════════════════════════════════════════════",
    `Generated by Honeypot AI Call Shield  •  ${new Date().toLocaleString()}`,
  ].join("\n");
}

export function CallShield() {
  const { toast } = useToast();
  const [isEnabled, setIsEnabled] = useState(false);
  const [callState, setCallState] = useState<CallState>("idle");
  const [turns, setTurns] = useState<Turn[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [verdict, setVerdict] = useState<{ scam: boolean; confidence: number; tactics: string[] } | null>(null);
  const [showFIR, setShowFIR] = useState(false);
  const transcriptRef = useRef<HTMLDivElement>(null);
  const isCancelled = useRef(false);

  const scrollDown = () => {
    setTimeout(() => {
      if (transcriptRef.current) {
        transcriptRef.current.scrollTop = transcriptRef.current.scrollHeight;
      }
    }, 100);
  };

  const addTurn = (role: Turn["role"], text: string) => {
    setTurns(prev => [...prev, { role, text, timestamp: new Date() }]);
    scrollDown();
  };

  const startSimulation = async () => {
    if (!isEnabled) {
      toast({ title: "Shield Offline", description: "Enable Call Shield first.", variant: "destructive" });
      return;
    }
    isCancelled.current = false;
    setCallState("ringing");
    setTurns([]);
    setVerdict(null);
    setShowFIR(false);

    await new Promise(r => setTimeout(r, 3000));
    if (isCancelled.current) return;
    setCallState("active");

    const sessionId = `call-${Date.now()}`;
    let conversationHistory: Array<{ role: string; content: string; timestamp: string }> = [];

    for (let i = 0; i < SCAMMER_SCRIPT.length; i++) {
      if (isCancelled.current) return;
      const line = SCAMMER_SCRIPT[i];
      await new Promise(r => setTimeout(r, i === 0 ? 800 : line.delay));
      if (isCancelled.current) return;

      addTurn("scammer", line.text);
      conversationHistory.push({ role: "scammer", content: line.text, timestamp: new Date().toISOString() });

      // Get AI agent response
      setIsProcessing(true);
      try {
        const resp = await fetch("/api/honeypot/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            sessionId,
            message: { sender: "scammer", text: line.text, timestamp: new Date().toISOString() },
            conversationHistory,
            metadata: { channel: "Voice", language: "English", locale: "IN" },
          }),
        });
        if (!resp.ok) throw new Error("API error");
        const data = await resp.json();
        if (isCancelled.current) return;

        const agentReply = data.agentReply || "Please repeat that again?";
        addTurn("agent", agentReply);
        conversationHistory.push({ role: "agent", content: agentReply, timestamp: new Date().toISOString() });

        // Speak via OmniDim
        playVoice(agentReply);

        await new Promise(r => setTimeout(r, 1800));
      } catch {
        addTurn("agent", "Arre, sorry beta. Can you repeat that? My phone signal is weak.");
      } finally {
        setIsProcessing(false);
      }
    }

    if (isCancelled.current) return;
    setCallState("ended");
    await new Promise(r => setTimeout(r, 1000));
    setVerdict({
      scam: true,
      confidence: 94,
      tactics: ["Impersonation — Bank official", "Urgency creation", "OTP phishing", "Card number extraction attempt"],
    });
    setCallState("verdict");
  };

  const endCall = () => {
    isCancelled.current = true;
    setCallState("idle");
    setTurns([]);
    setVerdict(null);
    setIsProcessing(false);
  };

  const downloadFIR = () => {
    const content = generateFIRFromCall(turns, { scam: true, intel: {} });
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `FIR_CallShield_${format(new Date(), "yyyyMMdd_HHmm")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Shell>
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold">Call Shield</h1>
            <p className="text-sm text-muted-foreground mt-0.5">Real-time voice interception and scam analysis</p>
          </div>

          {/* Toggle */}
          <div className="flex items-center gap-3">
            <span className="text-sm text-muted-foreground">Active Protection</span>
            <button
              onClick={() => {
                const next = !isEnabled;
                setIsEnabled(next);
                if (!next) endCall();
              }}
              className={cn(
                "relative w-12 h-6 rounded-full transition-colors duration-300 focus:outline-none",
                isEnabled ? "bg-primary" : "bg-muted"
              )}
            >
              <div className={cn(
                "absolute top-0.5 w-5 h-5 rounded-full bg-white shadow transition-transform duration-300",
                isEnabled ? "translate-x-6" : "translate-x-0.5"
              )} />
            </button>
            <span className={cn("text-xs font-medium", isEnabled ? "text-primary" : "text-muted-foreground")}>
              {isEnabled ? "Online" : "Offline"}
            </span>
          </div>
        </div>

        {!isEnabled ? (
          <div className="bg-card border border-dashed border-border rounded-xl flex flex-col items-center justify-center py-20 text-center">
            <Shield className="w-12 h-12 text-muted-foreground/30 mb-3" />
            <p className="text-muted-foreground text-sm">Enable Active Protection to intercept calls</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {/* Phone Panel */}
            <div className="bg-card border border-border rounded-xl flex flex-col items-center justify-center min-h-[380px] p-6 text-center">
              {callState === "idle" && (
                <div className="space-y-4">
                  <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto">
                    <PhoneCall className="w-8 h-8 text-primary/50" />
                  </div>
                  <p className="text-muted-foreground text-sm">Shield is listening for incoming calls</p>
                  <button
                    onClick={startSimulation}
                    className="bg-primary hover:bg-primary/90 text-primary-foreground text-sm font-medium px-5 py-2.5 rounded-lg transition-colors"
                  >
                    Simulate Incoming Scam Call
                  </button>
                </div>
              )}

              {callState === "ringing" && (
                <div className="space-y-4">
                  <div className="relative w-20 h-20 mx-auto">
                    <div className="absolute inset-0 rounded-full bg-orange-500/20 animate-ping" />
                    <div className="absolute inset-2 rounded-full bg-orange-500/20 animate-ping" style={{ animationDelay: "0.3s" }} />
                    <div className="relative w-20 h-20 rounded-full bg-orange-500/10 border border-orange-500/30 flex items-center justify-center">
                      <PhoneCall className="w-8 h-8 text-orange-400" />
                    </div>
                  </div>
                  <div>
                    <p className="font-semibold text-orange-400">Incoming Call</p>
                    <p className="text-sm text-muted-foreground font-mono mt-1">+91 98765 43210</p>
                    <p className="text-xs text-muted-foreground mt-1">Unknown / Suspicious</p>
                  </div>
                  <p className="text-xs text-primary animate-pulse">AI Agent intercepting...</p>
                </div>
              )}

              {(callState === "active" || callState === "ended") && (
                <div className="w-full space-y-5">
                  <div className="flex items-center justify-center gap-4">
                    <div className="flex flex-col items-center gap-1">
                      <div className="w-10 h-10 rounded-full bg-orange-500/10 border border-orange-500/30 flex items-center justify-center">
                        <Mic className="w-5 h-5 text-orange-400" />
                      </div>
                      <span className="text-xs text-muted-foreground">Scammer</span>
                    </div>
                    <div className="flex gap-0.5 items-end h-8">
                      {[3, 6, 9, 5, 8, 4, 7].map((h, i) => (
                        <div
                          key={i}
                          className={cn(
                            "w-1.5 rounded-full transition-all",
                            isProcessing ? "bg-primary animate-pulse" : "bg-border"
                          )}
                          style={{ height: `${h * 3}px`, animationDelay: `${i * 0.1}s` }}
                        />
                      ))}
                    </div>
                    <div className="flex flex-col items-center gap-1">
                      <div className="w-10 h-10 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center">
                        <Volume2 className="w-5 h-5 text-primary" />
                      </div>
                      <span className="text-xs text-muted-foreground">AI Agent</span>
                    </div>
                  </div>
                  {isProcessing && (
                    <p className="text-xs text-primary animate-pulse">Agent generating response...</p>
                  )}
                  <button
                    onClick={endCall}
                    className="flex items-center gap-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/30 text-sm px-4 py-2 rounded-lg transition-colors mx-auto"
                  >
                    <PhoneOff className="w-4 h-4" /> End Call
                  </button>
                </div>
              )}

              {callState === "verdict" && verdict && (
                <div className="space-y-4 w-full">
                  {verdict.scam ? (
                    <>
                      <div className="w-16 h-16 rounded-full bg-red-500/10 border border-red-500/30 flex items-center justify-center mx-auto">
                        <AlertTriangle className="w-8 h-8 text-red-400" />
                      </div>
                      <div>
                        <p className="text-lg font-bold text-red-400">Scam Call Confirmed</p>
                        <p className="text-sm text-muted-foreground mt-1">{verdict.confidence}% confidence</p>
                      </div>
                      <div className="text-left w-full space-y-1">
                        {verdict.tactics.map((t, i) => (
                          <div key={i} className="flex items-center gap-2 text-xs text-muted-foreground">
                            <div className="w-1 h-1 rounded-full bg-red-400 flex-shrink-0" />
                            {t}
                          </div>
                        ))}
                      </div>
                      <div className="flex gap-2 w-full">
                        <button
                          onClick={() => setShowFIR(true)}
                          className="flex-1 flex items-center justify-center gap-1.5 bg-primary hover:bg-primary/90 text-primary-foreground text-xs font-medium px-3 py-2 rounded-lg transition-colors"
                        >
                          <FileText className="w-3.5 h-3.5" /> Generate FIR
                        </button>
                        <button
                          onClick={endCall}
                          className="flex-1 flex items-center justify-center gap-1.5 bg-background hover:bg-card text-muted-foreground border border-border text-xs px-3 py-2 rounded-lg transition-colors"
                        >
                          New Simulation
                        </button>
                      </div>
                    </>
                  ) : (
                    <>
                      <CheckCircle className="w-12 h-12 text-emerald-400 mx-auto" />
                      <p className="font-semibold text-emerald-400">Legitimate Call</p>
                      <button onClick={endCall} className="bg-primary text-primary-foreground text-sm px-4 py-2 rounded-lg">Done</button>
                    </>
                  )}
                </div>
              )}
            </div>

            {/* Transcript */}
            <div className="bg-card border border-border rounded-xl flex flex-col">
              <div className="px-4 py-3 border-b border-border">
                <h3 className="font-medium text-sm">Live Transcript</h3>
              </div>
              <div ref={transcriptRef} className="flex-1 overflow-y-auto p-4 space-y-3 min-h-[300px]">
                {turns.length === 0 ? (
                  <p className="text-muted-foreground text-sm text-center py-10">
                    {callState === "idle" ? "Start a simulation to see live transcript" : "Waiting for call..."}
                  </p>
                ) : (
                  turns.map((turn, i) => (
                    <div key={i} className={cn("flex", turn.role === "agent" ? "justify-end" : "justify-start")}>
                      <div className={cn(
                        "max-w-[85%] rounded-lg p-3 text-sm border",
                        turn.role === "agent"
                          ? "bg-primary/10 border-primary/20 text-foreground"
                          : "bg-background border-border text-foreground"
                      )}>
                        <div className="flex items-center gap-2 mb-1">
                          <span className={cn("text-xs font-medium", turn.role === "agent" ? "text-primary" : "text-orange-400")}>
                            {turn.role === "agent" ? "AI Agent" : "Suspect"}
                          </span>
                          <span className="text-xs text-muted-foreground">{format(turn.timestamp, "HH:mm:ss")}</span>
                        </div>
                        <p className="leading-relaxed">{turn.text}</p>
                        {turn.role === "agent" && (
                          <button
                            onClick={() => playVoice(turn.text)}
                            className="mt-1.5 flex items-center gap-1 text-xs text-primary/60 hover:text-primary transition-colors"
                          >
                            <Volume2 className="w-3 h-3" /> Listen
                          </button>
                        )}
                      </div>
                    </div>
                  ))
                )}
                {isProcessing && (
                  <div className="flex justify-end">
                    <div className="bg-primary/10 border border-primary/20 rounded-lg px-4 py-2 flex items-center gap-2">
                      <span className="text-xs text-primary">Agent thinking</span>
                      <div className="flex gap-0.5">
                        {[0, 1, 2].map(i => (
                          <div key={i} className="w-1 h-1 bg-primary rounded-full animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* FIR Modal */}
      {showFIR && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4" onClick={() => setShowFIR(false)}>
          <div className="bg-card border border-border rounded-xl max-w-2xl w-full max-h-[85vh] flex flex-col shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between p-5 border-b border-border">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-primary" />
                <h2 className="font-semibold">FIR Report — Phone Fraud</h2>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={downloadFIR} className="flex items-center gap-1.5 text-xs bg-primary text-primary-foreground px-3 py-1.5 rounded-md hover:bg-primary/90 transition-colors">
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
                <button onClick={() => setShowFIR(false)} className="text-muted-foreground hover:text-foreground text-sm px-2">✕</button>
              </div>
            </div>
            <div className="overflow-y-auto flex-1 p-5">
              <pre className="text-xs font-mono text-foreground leading-relaxed whitespace-pre-wrap bg-background border border-border rounded-lg p-4">
                {generateFIRFromCall(turns, { scam: true, intel: {} })}
              </pre>
            </div>
            <div className="p-4 border-t border-border">
              <p className="text-xs text-muted-foreground">
                File at <a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer" className="text-primary underline">cybercrime.gov.in</a> or call <strong>1930</strong>
              </p>
            </div>
          </div>
        </div>
      )}
    </Shell>
  );
}
