import { useState, useRef, useEffect } from "react";
import { Shell } from "@/components/layout/Shell";
import { useGetSession, useFinalizeSession } from "@workspace/api-client-react";
import { useParams, useLocation } from "wouter";
import { ArrowLeft, Volume2, FileText, User, Bot, Download, CheckCircle } from "lucide-react";
import { Link } from "wouter";
import { playVoice, cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";

function generateFIR(session: any): string {
  const intel = session.extractedIntelligence || {};
  const date = format(new Date(session.startedAt), "dd/MM/yyyy");
  const time = format(new Date(session.startedAt), "HH:mm");
  const lines = [
    "═══════════════════════════════════════════════════════",
    "           FIRST INFORMATION REPORT (FIR)",
    "         Cybercrime / Online Financial Fraud",
    "═══════════════════════════════════════════════════════",
    "",
    `Date of Incident  : ${date}`,
    `Time of Incident  : ${time}`,
    `Case Reference    : ${session.sessionId}`,
    `Fraud Category    : ${session.scamType || "Online Fraud"}`,
    `Threat Score      : ${session.scamProbability}%`,
    `Channel           : ${session.channel}`,
    "",
    "───────────────────────────────────────────────────────",
    "SECTION 1: INCIDENT SUMMARY",
    "───────────────────────────────────────────────────────",
    "",
    session.agentNotes || `Suspected ${session.scamType || "scam"} detected via AI honeypot system.`,
    "",
    "───────────────────────────────────────────────────────",
    "SECTION 2: EXTRACTED INTELLIGENCE (EVIDENCE)",
    "───────────────────────────────────────────────────────",
    "",
    `Suspect Phone Numbers:`,
    ...(intel.phoneNumbers?.length ? intel.phoneNumbers.map((p: string) => `  • ${p}`) : ["  None detected"]),
    "",
    `UPI / Payment IDs:`,
    ...(intel.upiIds?.length ? intel.upiIds.map((u: string) => `  • ${u}`) : ["  None detected"]),
    "",
    `Bank Account Numbers:`,
    ...(intel.bankAccounts?.length ? intel.bankAccounts.map((b: string) => `  • ${b}`) : ["  None detected"]),
    "",
    `Phishing Links / URLs:`,
    ...(intel.phishingLinks?.length ? intel.phishingLinks.map((l: string) => `  • ${l}`) : ["  None detected"]),
    "",
    `Keywords / Tactics Used:`,
    ...(intel.suspiciousKeywords?.length ? intel.suspiciousKeywords.map((k: string) => `  • ${k}`) : ["  None detected"]),
    "",
    "───────────────────────────────────────────────────────",
    "SECTION 3: CONVERSATION TRANSCRIPT",
    "───────────────────────────────────────────────────────",
    "",
    ...(session.conversation || []).map((t: any, i: number) => {
      const role = (t.role === "agent" || t.role === "assistant") ? "AI Honeypot" : "Suspect";
      const ts = format(new Date(t.timestamp), "HH:mm:ss");
      return [`[${ts}] ${role}:`, t.content, ""];
    }).flat(),
    "───────────────────────────────────────────────────────",
    "SECTION 4: COMPLAINANT DETAILS (Fill before submission)",
    "───────────────────────────────────────────────────────",
    "",
    "Full Name         : ____________________________",
    "Mobile Number     : ____________________________",
    "Address           : ____________________________",
    "Amount Lost (₹)   : ____________________________",
    "Bank Name         : ____________________________",
    "Account Number    : ____________________________",
    "",
    "───────────────────────────────────────────────────────",
    "Submit this FIR at:",
    "  • National Cybercrime Reporting Portal: cybercrime.gov.in",
    "  • Helpline: 1930",
    "  • Nearest Police Station (Cybercrime Cell)",
    "═══════════════════════════════════════════════════════",
    `Generated by Honeypot AI  •  ${new Date().toLocaleString()}`,
    "═══════════════════════════════════════════════════════",
  ];
  return lines.join("\n");
}

export function SessionDetail() {
  const { id } = useParams();
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const { data: session, isLoading, error } = useGetSession(id || "");
  const finalizeMutation = useFinalizeSession();
  const scrollRef = useRef<HTMLDivElement>(null);
  const [showFIR, setShowFIR] = useState(false);
  const [firGenerated, setFirGenerated] = useState(false);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [session?.conversation]);

  if (!id) return null;

  const handleGenerateFIR = async () => {
    if (!session) return;
    // Finalize the session to update status, then show FIR
    if (session.status !== "complete") {
      try {
        await finalizeMutation.mutateAsync({ sessionId: id });
      } catch {
        // Ignore — still show the report
      }
    }
    setFirGenerated(true);
    setShowFIR(true);
  };

  const downloadFIR = () => {
    if (!session) return;
    const content = generateFIR(session);
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `FIR_${id}_${format(new Date(), "yyyyMMdd")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Shell>
      <div className="max-w-5xl mx-auto space-y-5">
        <Link href="/sessions" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Sessions
        </Link>

        {isLoading ? (
          <div className="animate-pulse h-96 bg-card border border-border rounded-lg" />
        ) : error || !session ? (
          <div className="p-5 border border-red-500/30 bg-red-500/10 text-red-400 rounded-lg text-sm">
            Session not found.
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Conversation */}
            <div className="lg:col-span-2 flex flex-col h-[calc(100vh-180px)]">
              <div className="bg-card border border-border rounded-lg flex flex-col h-full">
                <div className="px-5 py-4 border-b border-border flex items-center justify-between">
                  <div>
                    <h2 className="font-semibold">Interception Log</h2>
                    <p className="text-xs text-muted-foreground font-mono mt-0.5">{session.sessionId}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={cn(
                      "text-xs px-2.5 py-1 rounded-full border font-medium",
                      session.scamDetected
                        ? "bg-red-500/10 text-red-400 border-red-500/30"
                        : "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
                    )}>
                      {session.scamProbability}% threat
                    </span>
                    {session.scamType && (
                      <span className="text-xs bg-card border border-border px-2 py-0.5 rounded text-muted-foreground">
                        {session.scamType}
                      </span>
                    )}
                  </div>
                </div>

                <div ref={scrollRef} className="flex-1 overflow-y-auto p-5 space-y-4">
                  {(!session.conversation || session.conversation.length === 0) && (
                    <p className="text-center text-muted-foreground text-sm py-10">No messages yet.</p>
                  )}
                  {session.conversation?.map((turn: any, idx: number) => {
                    const isAgent = turn.role === "agent" || turn.role === "assistant";
                    return (
                      <div key={idx} className={cn("flex", isAgent ? "justify-end" : "justify-start")}>
                        <div className={cn(
                          "max-w-[78%] rounded-lg p-3.5 border text-sm",
                          isAgent
                            ? "bg-primary/8 border-primary/20 text-foreground"
                            : "bg-background border-border text-foreground"
                        )}>
                          <div className="flex items-center justify-between gap-4 mb-1.5">
                            <span className={cn("text-xs font-medium flex items-center gap-1", isAgent ? "text-primary" : "text-orange-400")}>
                              {isAgent ? <Bot className="w-3.5 h-3.5" /> : <User className="w-3.5 h-3.5" />}
                              {isAgent ? "AI Agent (Ramesh Kumar)" : "Suspect"}
                            </span>
                            <span className="text-xs text-muted-foreground">{format(new Date(turn.timestamp), "HH:mm:ss")}</span>
                          </div>
                          <p className="leading-relaxed whitespace-pre-wrap">{turn.content}</p>
                          {isAgent && (
                            <button
                              onClick={() => playVoice(turn.content)}
                              className="mt-2 flex items-center gap-1 text-xs text-primary/60 hover:text-primary transition-colors"
                            >
                              <Volume2 className="w-3.5 h-3.5" /> Listen
                            </button>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Right panel */}
            <div className="space-y-4">
              {/* Intelligence */}
              <div className="bg-card border border-border rounded-lg p-4">
                <h3 className="font-medium text-sm mb-3">Extracted Intelligence</h3>
                <div className="space-y-3">
                  {[
                    { label: "Phone Numbers", items: session.extractedIntelligence?.phoneNumbers, color: "text-yellow-400 bg-yellow-500/10 border-yellow-500/20" },
                    { label: "UPI IDs", items: session.extractedIntelligence?.upiIds, color: "text-orange-400 bg-orange-500/10 border-orange-500/20" },
                    { label: "Phishing Links", items: session.extractedIntelligence?.phishingLinks, color: "text-red-400 bg-red-500/10 border-red-500/20" },
                    { label: "Bank Accounts", items: session.extractedIntelligence?.bankAccounts, color: "text-red-400 bg-red-500/10 border-red-500/20" },
                    { label: "Keywords", items: session.extractedIntelligence?.suspiciousKeywords, color: "text-slate-400 bg-slate-500/10 border-slate-500/20" },
                  ].map(({ label, items, color }) => (
                    <div key={label}>
                      <p className="text-xs text-muted-foreground mb-1">{label}</p>
                      {items?.length ? (
                        <div className="flex flex-wrap gap-1">
                          {items.map((item: string, i: number) => (
                            <span key={i} className={cn("text-xs px-2 py-0.5 rounded border font-mono break-all", color)}>{item}</span>
                          ))}
                        </div>
                      ) : (
                        <p className="text-xs text-muted-foreground/60">None detected</p>
                      )}
                    </div>
                  ))}
                </div>

                {session.agentNotes && (
                  <div className="mt-3 p-3 bg-background border border-border rounded text-xs text-muted-foreground leading-relaxed">
                    <span className="text-primary font-medium block mb-1">Agent Notes</span>
                    {session.agentNotes}
                  </div>
                )}
              </div>

              {/* FIR Button */}
              <div className="bg-card border border-border rounded-lg p-4 space-y-3">
                <h3 className="font-medium text-sm">Generate FIR Report</h3>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  Generate a ready-to-file First Information Report with all extracted evidence for submission to cybercrime.gov.in or your nearest police station.
                </p>
                <button
                  onClick={handleGenerateFIR}
                  disabled={finalizeMutation.isPending}
                  className="w-full flex items-center justify-center gap-2 bg-primary hover:bg-primary/90 text-primary-foreground text-sm font-medium px-4 py-2.5 rounded-md transition-colors disabled:opacity-60"
                >
                  {finalizeMutation.isPending ? (
                    <><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
                  ) : firGenerated ? (
                    <><CheckCircle className="w-4 h-4" /> View FIR Report</>
                  ) : (
                    <><FileText className="w-4 h-4" /> Generate FIR Report</>
                  )}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* FIR Modal */}
        {showFIR && session && (
          <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4" onClick={() => setShowFIR(false)}>
            <div className="bg-card border border-border rounded-xl max-w-2xl w-full max-h-[85vh] flex flex-col shadow-2xl" onClick={e => e.stopPropagation()}>
              <div className="flex items-center justify-between p-5 border-b border-border">
                <div className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-primary" />
                  <h2 className="font-semibold">FIR Report — Ready to File</h2>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={downloadFIR}
                    className="flex items-center gap-1.5 text-xs bg-primary text-primary-foreground px-3 py-1.5 rounded-md hover:bg-primary/90 transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" /> Download
                  </button>
                  <button onClick={() => setShowFIR(false)} className="text-muted-foreground hover:text-foreground text-sm px-2">✕</button>
                </div>
              </div>
              <div className="overflow-y-auto flex-1 p-5">
                <pre className="text-xs font-mono text-foreground leading-relaxed whitespace-pre-wrap bg-background border border-border rounded-lg p-4">
                  {generateFIR(session)}
                </pre>
              </div>
              <div className="p-4 border-t border-border bg-primary/5">
                <p className="text-xs text-muted-foreground">
                  File this report at{" "}
                  <a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer" className="text-primary underline">cybercrime.gov.in</a>
                  {" "}or call <strong>1930</strong> (National Cybercrime Helpline)
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </Shell>
  );
}
